### ISSUE TITLE
VSTS Release DigitalOcean Droplet

### ISSUE THREAD

**Issue by BillChirico** [marceloavf/digitalocean-tools-vsts#6]
Is it possible to create a VSTS release pipeline to deploy a docker image to a DigitalOcean Droplet?

**Comment by marceloavf** [comment]
Hey @BillChirico,

It's think that's possible, I can create a task to run some [ssh](https://github.com/mscdex/ssh2) against the server into Azure DevOps task to do that so.

Or if you have a bit of a hurry, you can use [SSH task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/ssh?view=vsts) to run some code in the DigitalOcean Droplet.

Do you have any code example of it?

**Comment by marceloavf** [comment]
Closed due to no response.

**Comment by marceloavf** [comment]
Extra info:

We are using DigitalOcean Spaces as docker image repository, using this:

```
version: '3'
services:
  registry:
    image: registry:2
    ports:
      - '5000:5000'
    environment:
      - REGISTRY_STORAGE=s3
      - REGISTRY_HTTP_SECRET=<key>
      - REGISTRY_STORAGE_S3_ACCESSKEY=<key>
      - REGISTRY_STORAGE_S3_SECRETKEY=<key>
      - REGISTRY_STORAGE_S3_BUCKET=<bucket-name>
      - REGISTRY_STORAGE_S3_REGION=digitalocean-nyc3
      - REGISTRY_STORAGE_S3_REGIONENDPOINT=https://nyc3.digitaloceanspaces.com/
      - REGISTRY_STORAGE_DELETE_ENABLED=true
```

After that, we use this 5000 port to send the image or update it, it can be an extension too.

For example:
```
docker.exe push localhost:5000/app-repository/app-name:1.4.52
```
